### ISSUE TITLE
Deeper section levels required in this GM/T standard

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/gmt-0015-2012#1]
Asciidoctor only allows 5 by default but this document has 7 levels of sections.

@opoudjis how can we enable this?

**Comment by opoudjis** [comment]
As with footnotes having to be only one paragraph long, Asciidoctor delights in telling you what you should do: https://github.com/asciidoctor/asciidoctor/issues/825. As the tone of that exchange suggests, asking this to be added into Asciidoctor is pointless (and that's lists, which are rather more benign than headers).

http://discuss.asciidoctor.org/Is-there-any-way-to-have-heading-deeper-than-5-td5513.html

> If you want deeper levels, you use discrete headings (at the discrete style) or block titles. But then you have to handle the numbering yourself (either explicitly or through an extension).

Discrete headings have manually coded headings, so they're not wonderful, but they will kind of work. Then again, discrete headings are not supported in our current setup.

So:

````
== Section 1

=== Section 1.2

==== Section 1.2.3

===== Section 1.2.3.4

[discrete]
===== Section 1.2.3.4.5

.Section 1.2.3.4.5.6.7

XXXX
````

Renders into HTML with default renderer as:

````
<div class="sect1">
<h2 id="_section_1">Section 1</h2>
<div class="sectionbody">
<div class="sect2">
<h3 id="_section_1_2">Section 1.2</h3>
<div class="sect3">
<h4 id="_section_1_2_3">Section 1.2.3</h4>
<div class="sect4">
<h5 id="_section_1_2_3_4">Section 1.2.3.4</h5>
<h5 id="_section_1_2_3_4_5" class="discrete">Section 1.2.3.4.5</h5>
<div class="paragraph">
<div class="title">Section 1.2.3.4.5.6.7</div>
<p>XXXX</p>
</div>
</div>
</div>
</div>
</div>
</div>
````

That currently crashes our renderer, because I have not implemented discrete titles at all. Note that if I do implement discrete titles, the processor will still have no idea whether this is a 6th or 7th level title, unless I start inserting asciiISO specific parameters as attributes; at that stage, we might as well just make it

````
[level=7]
===== Section 1.2.3.4.5.6.7
````

So, the only real way to do this with coherent ISOXML output is to introduce a new ISO-specific attribute to AsciiISO, telling the ISOXML conversion to ignore the notated level, and use the attribute level instead.

Before I proceed with this, can you confirm that you really, really want this? HTML only goes down to `<h6>`, which means that a 7th header is going to end up marked up in HTML as `<h6>` anyway. So 7 levels of depth is going to mess up downstream document processing, in HTML and in Word HTML. (The reason Dan Allen claims that he is abiding by HTML limits in going down to 5 levels is that he already uses `<h1>` for the document title.) If we can avoid doing this, we should.

The alternative of block titles, I have to see, is far less painful:

````
. 4.5.11.2.2.1 Definition
[source]
----
id-ce-authorityKeyIdentifier OBJECTIDENTIFIER   ::= {id-ce 35}
----
````

But you still have to manually put the numbering in; and I would need to change code still, because I currently ignore block titles, too.

**Comment by ronaldtse** [comment]
Then it sounds like we should not be limited to the `h1`..`h6` tags at all. They are supposed to be styling tags, not semantic tags...

**Comment by opoudjis** [comment]
Dan Allen's primary object is actually about maintaining the stylesheets for the h7 equivalent. In any case, we will clearly need to render a 7th level section idiosyncratically, no matter what happens.

So. 

* Block titles, which forces explicit numbering and does not retain level numbers, but doesn't go outside Asciidoctor?

Not really an option.

* Discrete titles, ditto?

Not really an option either.

* Marked up level with discrete titles, which preserves level numbers in ISOXML and autonumbering, but is outside of Asciidoctor proper?

An option, will require coding work.

* Avoid more than 6 levels?

From what I gather, not an option.

**Comment by ronaldtse** [comment]
Asciidoctor has 2 parts -- an input processing part for Asciidoctor syntax ("AD syntax"), and an output generation for HTML. We don't use the latter part at all, it is replaced with `isodoc`. Isodoc should not have explicit section level tags anyway (i.e. `h{n}`: h1, h2...).

Ideally the flow is:

Asciidoctor-ISO input -> Metanorma model -> Isodoc -> HTML

So this means we want Asciidoctor-ISO to support the 7-level sections.

**Comment by opoudjis** [comment]
The solution will be 

````
[level=7]
===== Heading
````

Asciidoctor syntax will continue to reject `=======`.

The IsoDoc rendering of such headings will need to do *something*; I suspect it will just be `<h6>`. The autonumbering of course should work regardless.

**Comment by ronaldtse** [comment]
Can't we just override this RegEx to support more levels?

https://github.com/asciidoctor/asciidoctor/blob/20c8c9bdc75dc8cb4a3e168c9c61751ed5182139/lib/asciidoctor.rb#L645

The `secnum` for example is used here for HTML5:

https://github.com/asciidoctor/asciidoctor/blob/20c8c9bdc75dc8cb4a3e168c9c61751ed5182139/lib/asciidoctor/converter/html5.rb#L294

**Comment by opoudjis** [comment]
I'm deeply uncomfortable with stepping outside the Asciidoctor syntax: it will break whatever other tools might interact with our Asciidoctor (and we can't assume that only our tooling will). Not to mention that I have zero confidence updates to Asciidoctor won't break any such overrides.

**Comment by ronaldtse** [comment]
What are the possibilities that we will interact with other asciidoctor extensions?

We are only using the asciidoctor parser for input parsing, not its output. Asciidoctor upgrades already affect us in the same way.

**Comment by opoudjis** [comment]
You're the boss, but:

> What are the possibilities that we will interact with other asciidoctor extensions?

Non-zero: we don't know that people won't want to generate a asciidoctor file through a third-party tool, or postprocess the asciidoctor file through a third-party tool, before it ends up with metanorma. We should not be assuming anything about how the asciidoctor file is generated.

> Asciidoctor upgrades already affect us in the same way.

Not so. We have not had any dependency on unexposed internal methods and constants of the Asciidoctor code (`AtxSectionTitleRx`?!). This would introduce it.

I'll introduce `=======` if you insist, but I do not consider this a good idea at all.

**Comment by opoudjis** [comment]
I have implemented the required behaviour:

````
  it "extends clause levels past 5" do
    expect(strip_guid(Asciidoctor.convert(<<~"INPUT", backend: :iso, header_footer: true))).to be_equivalent_to <<~"OUTPUT"
    #{ASCIIDOC_BLANK_HDR}

    == Clause1

    === Clause2

    ==== Clause3

    ===== Clause4

    ====== Clause 5

    [level=6]
    ====== Clause 6

    [level=7]
    ====== Clause 7A

    [level=7]
    ====== Clause 7B

    [level=6]
    ====== Clause 6B

    ====== Clause 5B

    INPUT
    #{BLANK_HDR}
    <sections>
  <clause id="_" inline-header="false" obligation="normative">
  <title>Clause1</title>
  <clause id="_" inline-header="false" obligation="normative">
  <title>Clause2</title>
  <clause id="_" inline-header="false" obligation="normative">
  <title>Clause3</title>
  <clause id="_" inline-header="false" obligation="normative"><title>Clause4</title><clause id="_" inline-header="false" obligation="normative">
  <title>Clause 5</title>
<clause id="_" inline-header="false" obligation="normative">
  <title>Clause 6</title>
<clause id="_" inline-header="false" obligation="normative">
  <title>Clause 7A</title>
</clause><clause id="_" inline-header="false" obligation="normative">
  <title>Clause 7B</title>
</clause></clause><clause id="_" inline-header="false" obligation="normative">
  <title>Clause 6B</title>
</clause></clause>




<clause id="_" inline-header="false" obligation="normative">
  <title>Clause 5B</title>
</clause></clause>
</clause>
</clause>
</clause>
</sections>
</iso-standard>
    OUTPUT
````

**Comment by opoudjis** [comment]
And since this works and doesn't break Asciidoctor syntax or depend on unexposed features of the Asciidoctor code, I recommend we go with this. Not checking in or documenting this yet.

**Comment by ronaldtse** [comment]
Right, this works (when the published gem contains this update). And we need to appropriately document this (does this also apply to ISO or only GB? I suspect all of them). Thanks!

**Comment by ronaldtse** [comment]
I've pushed the update that uses the new `[level=X]` syntax, but the gem isn't supporting it yet.

**Comment by opoudjis** [comment]
Right, I haven't pushed it yet, because I was waiting for your approval. I will within the hour.

**Comment by opoudjis** [comment]
Also doing validation message that levels do not exceed 7, as required in ISO/IEC DIR 2.

**Comment by ronaldtse** [comment]
So indeed the 7 levels are required by DIR 2, good thing we found out via GB :wink:

**Comment by opoudjis** [comment]
Oh I knew that, I just couldn't enforce it within Asciidoctor, because the preexisting structure didn't let me create 7 levels.

Please close this ticket.
